---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.redis.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "mds.labels" . | nindent 4 }}
type: Opaque
stringData:
  connection-string: {{ required "Redis connection string is required" (index .Values.secrets.redis.data "connection-string") | quote }}
  mds-cluster-prefix: {{ required "Redis MDS cluster prefix is required" (index .Values.secrets.redis.data "mds-cluster-prefix") | quote }}